/**
 * 将 admin/dist/index.html 转为可内联的 JS 模块
 * 运行: node scripts/build-admin.mjs
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const html = readFileSync(resolve(root, 'admin/dist/index.html'), 'utf-8');

const output = `// Auto-generated by scripts/build-admin.mjs — do not edit manually
const HTML = ${JSON.stringify(html)};
export function getAdminHTML() { return HTML; }
`;

writeFileSync(resolve(root, 'admin.js'), output, 'utf-8');
console.log('✓ admin.js generated (%d KB)', Math.round(output.length / 1024));